---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: github-instavote
  namespace: instavote
spec:
  address: https://github.com/manquintero/instavote-deploy.git
  secretRef:
    name: github-token
  type: github
