---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: result
  namespace: instavote
spec:
  chart:
    spec:
      chart: ./helm/charts/result
      sourceRef:
        kind: GitRepository
        name: instavote
  interval: 1m0s
  targetNamespace: instavote
