apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- vote-canary.yaml
- deployment.yaml
replicas:
  - name: vote
    count: 0

commonAnnotations:
  supported-by: support@fluxcd.io

configMapGenerator:
  - name: vote-options
    envs:
     - options.env
